### ISSUE TITLE
[Insight] Code should not be duplicated

### ISSUE THREAD

**Issue by sstok** [rollerworks/PasswordStrengthBundle#10]
**[in src/Rollerworks/Bundle/PasswordStrengthBundle/Command/BlacklistDeleteCommand.php, line 29](https://github.com/rollerworks/PasswordStrengthBundle/blob/master/src/Rollerworks/Bundle/PasswordStrengthBundle/Command/BlacklistDeleteCommand.php#L29)**

> The next 29 lines appear both in `src/Rollerworks/Bundle/PasswordStrengthBundle/Command/BlacklistDeleteCommand.php:29` and `src/Rollerworks/Bundle/PasswordStrengthBundle/Command/BlacklistUpdateCommand.php:29`.

```php
            ->setName('rollerworks-password:blacklist:delete')->setDescription('removes passwords from your blacklist database')
            ->addArgument('passwords', InputArgument::OPTIONAL | InputArgument::IS_ARRAY, 'space separated list of words to remove')
            ->addOption('file', null, null, 'Text file to read for deletion, every line is considered one word');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if (!$input->getArgument('passwords') && !$input->getOption('file')) {
            $output->writeln('<error>No passwords or file-option given.</error>');

            return;
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cbae8797-e80a-495f-875c-ab1581cc4b18/analyses/18)_

**Comment by cordoval** [comment]
I am attempting this in #32

**Comment by cordoval** [comment]
@sstok after merging #32 it is good to close this one
