### ISSUE TITLE
How/where does validation happen?

### ISSUE THREAD

**Issue by softrare** [rollerworks/PasswordStrengthBundle#105]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

I have this included in my User entity class. 

    /**
     * @RollerworksPassword\PasswordRequirements(requireLetters=true, requireNumbers=true, requireCaseDiff=true)
     * @RollerworksPassword\PasswordStrength(minLength=9, minStrength=4)
     */
    protected $plainPassword;

How does the validation happen though? When I submit a form with plainPassword included as repeattype element nothing happens meaning a password which should not validate gets through just fine. Fix is probably simple but I don't see any documentation on this. Thanks!

**Comment by sstok** [comment]
It depends on how you use the Form component, if you bind the entity to a form it will automatically validate.

If the value is `null` or an empty string the validator will ignore the value
https://github.com/rollerworks/PasswordStrengthValidator/blob/master/src/Validator/Constraints/PasswordRequirementsValidator.php#L26 (this is the same for all Symfony Constraints btw), if you want to require this field always has a value add https://symfony.com/doc/current/reference/constraints/NotBlank.html before the other constraints.

**Comment by softrare** [comment]
Hi! Thank you for your reaction. How do you bind the entity to a form? Isn't the entity bound to the form by the controller by something like `$this->createForm(UserType::class, $user)` ? If that's what you mean, it doesn't work for me unfortunately :( I understand the case where the password field is left blank, but I mean specifically cases where it is filled. 

The only way to make the library work up until now what I have to do is this in the Type declaration:
```
$builder->add('plainPassword', RepeatedType::class, array(
...
            'constraints' => [ new RollerworksPassword\PasswordStrength(['minLength'=>9, 'minStrength'=>4]),
                                new RollerworksPassword\PasswordRequirements(['requireLetters'=>true, 'requireNumbers'=>true, 'requireCaseDiff'=>true, 'requireSpecialCharacter'=>true])],
...
}
```

As multiple forms are working with the same entity I would love to make this work with the annotation instead. Thanks again for your help!

**Comment by sstok** [comment]
Sorry for the late reply (I had to deal with some personal issues).

I suggest you use the https://symfony.com/slack `#support` channel as they are able to help you better, as this is a more complex support question I don't have the time help with this.
