### ISSUE TITLE
Deprecation in Symfony 6

### ISSUE THREAD

**Issue by mdeherder** [rollerworks/PasswordStrengthBundle#111]
Method `"Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()"` might add `"TreeBuilder"` as a native return type declaration in the future. 
Do the same in implementation `"Rollerworks\Bundle\PasswordStrengthBundle\DependencyInjection\Configuration"` now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by sstok** [comment]
Should be fixed by #112
