### ISSUE TITLE
I18N integration ?

### ISSUE THREAD

**Issue by Soullivaneuh** [rollerworks/PasswordStrengthBundle#27]
It would be useful to integrate translations on this bundle.

With this way, contributors could propose some default translations. :+1: 

What do you think ? I can work on a PR if you want it.

Thanks.

**Comment by sstok** [comment]
With the merging of #47 I may have some ideas to make this possible :)

If the strength is to low we can check what is missing, and include this in the message.
`Your password needs to be at least at strength level "{{ min_strength}}", current level is "{{ current_strength }}", try adding {{ strength_tips }}".` which result in something like `Your password needs to be at least at strength level "strong", current level is "weak"', try adding numbers and special chars.".`

**Comment by Soullivaneuh** [comment]
Seems good, why not!

Sorry for no news, quite busy at this moment.

**Comment by sstok** [comment]
Done in v1.5
