### ISSUE TITLE
create a service for strong password generation

### ISSUE THREAD

**Issue by cordoval** [rollerworks/PasswordStrengthBundle#36]
this shouldn't be that hard and it is a fine complement to a password validator

**Comment by sstok** [comment]
Generating a good password is more changeling than it seems.
There is already a pretty good library for this: https://github.com/ircmaxell/RandomLib

I actually like split the bundle up in to components, and move the password blacklist to its own bundle :)
All with BC of course ;)

**Comment by cordoval** [comment]
true, i agree now, let me close this puppy
