### ISSUE TITLE
Validation doesn't work on repeated form type

### ISSUE THREAD

**Issue by Garfield-fr** [rollerworks/PasswordStrengthBundle#52]
Hi,

I use your bundle to validate the password. But i have a form to change the password with form type repeated. In this situation, the validation doesn't work.

Why ?

Thank's for your help

Bertrand

**Comment by Garfield-fr** [comment]
i found my problem in class PasswordRequirementsValidator. If the value is missing, the validator doesn't work because, you are this on the top of validation:

```
if (null === $value || '' === $value) {
```

This option "minLength" is ignored in this case.

Thank's

**Comment by sstok** [comment]
Thanks for reporting, I will look into solving this shortcoming.

**Comment by Garfield-fr** [comment]
You are the same check on PasswordStrengthValidator.

Thanks

**Comment by sstok** [comment]
I think I misunderstood you :)

We can't remove the `if (null === $value || '' === $value) {` as a field can also be optional.
To requiring a value you must use the http://symfony.com/doc/current/reference/constraints/NotBlank.html constraint first and then the PasswordStrengt will be applied when the value is not blank.

I will update the documentation to make this more clear.

**Comment by sstok** [comment]
done in 886077d4129fed49431fffb8a3b6105c996cfe5d

**Comment by Garfield-fr** [comment]
ok, no problem. I added a NotBlank Validator on field.

Thanks
