### ISSUE TITLE
2.0 roadmap

### ISSUE THREAD

**Issue by sstok** [rollerworks/PasswordStrengthBundle#53]
These are some idea's for 2.0 (semver).

_The 1.x branch will be maintained for as long as possible. Features will happen as much in the master (2.0) branch._
- Require Symfony 2.7 LTS (instead of 2.3)
- Require PHP ~~5.4~~ 5.5 (instead of PHP 5.3)
- Drop BC layers
- Move validators to a separate component (they are also usable without the FrameworkBundle); The blacklist validator can have it's own component.

**Comment by sstok** [comment]
Instead of breaking everything I'm planning on making an upgrade as painless as possible (similar to Symfony upgrades):

1.x (v1.6.0)

* Move the validators outside of the bundle (BC is preserved by requiring the separate components);
* Keep PHP 5.3 compatibility;

2.x 

* PasswordStrengthBundle is deprecated in favor of the components;
* Components require PHP 5.4 (5.5?) and Symfony 2.8;
* PasswordBlacklistBundle which integrates the Blacklist validator into a Symfony application (try to decouple from the FrameworkBundle);
* Components I18n files are handled using [Puli](http://puli.io/) :dog: ;

2.0 is basically 1.x but with all the deprecations and BC layers removed, plus there is no more need to have a bundle (except for the blacklist validator and it commands).

**Comment by Soullivaneuh** [comment]
> Require PHP 5.4 (instead of PHP 5.3) (consider 5.5?)

According to [PHP EOL](http://php.net/eol.php), 5.4 is not supported anymore. So bump to PHP 5.5 seems to be correct.

BTW, you will able to use short array syntax and `::class` trick, this is cool! :+1: 

> Components I18n files are handled using Puli :dog: ;

I'm curious about Puli. For what using it and how? :-)

Another idea: Silex integration of the validator? See: https://github.com/Soullivaneuh/IsoCodesValidator/blob/master/src/Provider/IsoCodesValidatorServiceProvider.php

**Comment by sstok** [comment]
> I'm curious about Puli. For what using it and how? :-)

Puli makes it possible to easily load files (like translations) without having to resort to hacks like adding a translation resource to the Translator service (which will btw break with application overwrites! see a more complex example at https://github.com/rollerworks/RollerworksSearchBundle/blob/7302447e4d17b6e9c08d94d87e2cd693c1dba691/src/Rollerworks/Bundle/SearchBundle/DependencyInjection/Compiler/TranslatorPass.php ) Or mirroring them in the resources folder, see https://github.com/rollerworks/RollerworksSearchBundle/blob/master/src/DependencyInjection/RollerworksSearchExtension.php#L58-L65 

But letting the Framework integration handle this.
This will be done later btw, because it's not supported yet :cry: but it will make integration easier and less hacky.

Silex is definitely something I want to add :+1:

**Comment by Soullivaneuh** [comment]
> Puli makes it possible to easily load files (like translations) without having to resort to hacks like adding a translation resource to the Translator service

I have to take time to really study Puli. I'm interested to see your work about that too. :+1: 

About PHP, 2.0 is not out yet and PHP 5.5 is EOL too now. :tongue: 

Maybe take profit to bump minimum requirement to 5.6?

**Comment by Soullivaneuh** [comment]
Another idea for 2.x: Change translation id to label code.

This will be painful to manage IMHO.

This is what I deed for mine: https://github.com/Soullivaneuh/IsoCodesValidator/pull/92

**Comment by Soullivaneuh** [comment]
> Silex is definitely something I want to add :+1: 

About that, I have another proposition.

You're project is a Symfony bundle, that is not very mandatory and will not be really true if you provide silex integration.

Why not rename/create the project to `PasswordStrengthValidator` as a library?

On your source directory, you'll have the constraint/validator logic.

For bundle part, all can be on `Bundle` directory and for Silex, `Provider` directory.

You can also create a `Bridge` directory containing a `Symfony` and `Silex` folders.

Here my actual directory structure: https://github.com/Soullivaneuh/IsoCodesValidator/tree/master/src

**Comment by sstok** [comment]
Thanks for the proposals 👍 definitely will look at that, I always try to follow package design very strictly but in this case it's not a problem as the main dependency for the integration is already met.

I can even accept PHP 7 😄 the reason for choosing 5.5 is that it it's the minimum version required by Symfony 3. If there no objections by other users we can switch to PHP 5.6 in 2.0 of this package.

**Comment by Soullivaneuh** [comment]
Another example of Symfony integration I made with @greg0ire using `Bridge` folder: https://github.com/greg0ire/enum/tree/master/src

This project porpose integration for symfony validator and form components. No need for bundle here. :wink:

**Comment by sstok** [comment]
@Soullivaneuh do think it would be better rename this repository (and package, for 2.0 at least) or create a new repository (with the git commits of this repository, basically a source fork) and make that the the "2.0" release stream?

**Comment by sstok** [comment]
Because of the problems mentioned in https://github.com/Soullivaneuh/IsoCodesValidator/pull/116 I'm hesitant on using a combined package for Silex.

Basically we need a Silex ServiceProvider (package), Symfony Bundle (package), and Validator package.

If Silex doesn't change to much (in terms of BC layers) we can keep all together, adding some checks is acceptable but method signature changes are a nightmare 👻

The Symfony Validator Component and FrameworkBundle are developed and released in-sync, so keeping the password validators and Symfony Bundle together is no problem in terms of compatibility. But I need some insight from those who actually use it 😃

About the separate packages, I recently discovered https://github.com/splitsh/lite, where the full version allows to automatically split the Validator to READ-ONLY repositories. 

So we end up with:

* PasswordStrengthValidator (Monolith repository of the PasswordValidator or Validator and Symfony Bundle only. Needs a better name)
* PasswordStrengthValidator-library (Validators and Translations) [READ-ONLY]
* PasswordStrengthValidator-Bundle (Symfony Bundle) [READ-ONLY]
* PasswordStrengthValidator-Silex (Silex plug-in) [READ-ONLY]

@stof Do you have any suggestions/comments on how we can tackle this problem?

----

Disclaimer: I can't promise this will happen any time soon, I already have allot of other things to do (RollerworksSearch v2, Park-Manager, SkeletonDancer) and not to mentioned taking care of some unrelated "personal problems", so any help with development is welcome 👍

Don't worry about the current development, this bundle pretty stable 😉 but any help is welcome.

**Comment by Soullivaneuh** [comment]
> Because of the problems mentioned in Soullivaneuh/IsoCodesValidator#116 I'm hesitant on using a combined package for Silex.

Didn't understand the problem, I have to investigate.

After all, each solution has pro and cons. It's depends of what you need/can. :wink:

**Comment by Soullivaneuh** [comment]
@sstok FYI: https://github.com/composer/composer/issues/5505#issuecomment-274503947

**Comment by sstok** [comment]
Thanks, lets hope they fix this ☹️

**Comment by stof** [comment]
another argument in favor of separate packages: it allows making another version of the integration package when a new version of Silex comes out, while supporting 2 different versions of Silex in your main package may be harder.

If you follow semver on your package, you may not even need a main repo being split. You could just treat the Silex integration as a consumer package as far as your main package is concerned.
As your package is quite small, following semver strictly should not be hard. Twig manages to do it since the 1.0 release, and it has not need to create a second maintenance branch until the work on the new major release. And such a setup is also what ZF is using now. It avoids the need to setup a realtime splitting system.

**Comment by sstok** [comment]
I source-forked (all original commits and authorship preserved) the bundle into a library https://github.com/rollerworks/PasswordStrengthValidator and will update this bundle (v2.0) in the upcoming days.

I also took the time to fix some minor issues (which were already planned for 2.0 of this bundle).
If you notice you something is wrong or missing please open an issue/pull request in the new repository 👍

**Comment by sstok** [comment]
It's here #80! please review and give any comments you have 👍

**Comment by sstok** [comment]
It is done 🎉
