### ISSUE TITLE
Password Strength Check

### ISSUE THREAD

**Issue by rtoledof** [rollerworks/PasswordStrengthBundle#54]
I'm trying to use the bundle but when I try to create a user and generate a password for example $2y$15$9ce44cdaed44a94f25789efCWKw.ziTvGBN4WRTmtgsg1Yce2BKo2 this is the password I'm generating when try to save the entity in database the form return an error and the error said password too weak and I think this password isn't weak or I'm wrong. What is the problem??? I tried to change the  minStrength parameter but the error continues

**Comment by mennowame** [comment]
It looks like you confused the generated password with the hashed version of that password. The string you pasted here looks like the salted & hashed version of a password. Maybe you can first find the original password that you generated and check if that meets all the strength requirements.

**Comment by rtoledof** [comment]
I tried to use a random string generator to create the password. Now I'm passing a string like "pKeg0Ndvd8BhOVa1NQPDIguf2FuszrWE0w4BgSPbP1Vyp35ThL" and the strength checker told me "Your password must include both upper and lower case letters." What is the problem now?? Any can help me??

**Comment by mennowame** [comment]
A bit difficult to help without further context. To help you find the problem/solution: This is not in the strength checker / strength Validator, but in the requirements Validator

**Comment by rtoledof** [comment]
I think was my problem because I was apply the assert to the field password and the password is encrypt for symfony automatically I solve it apply the assert to the plainPassword field from the  FOSUserBundle sorry.

**Comment by sstok** [comment]
No problem ;) glad you solved it. Thanks mennowame for helping.
