### ISSUE TITLE
Fatal error: Allowed memory size of 1073741824 bytes exhausted

### ISSUE THREAD

**Issue by ngocongcan** [rollerworks/PasswordStrengthBundle#75]
Hi contributors,

I got this error "Fatal error: Allowed memory size of 1073741824 bytes exhausted" when run composer update recently. This seems your update cause this error. Please take a look, please !

**Comment by sstok** [comment]
Try updating your Composer version, clear the cache, and if possible remove the composer.lock file as this could cause a big computation.

Things like these are unlikely to be related to this library, as the last release is from 2016 and haven't received any reports with this problem.

**Comment by ngocongcan** [comment]
You are right, I have used the old Composer version. It works when I upgrade newest composer version. However, I did not have this issue before. 
Thank you!
