### ISSUE TITLE
Error: the service must be public as it can be lazy-loaded

### ISSUE THREAD

**Issue by Lionel09** [rollerworks/PasswordStrengthBundle#84]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

I have just updated my libs to the last version of SF2.8 (v2.8.24 to v2.8.25) and PasswordStrengthBundle (v1.6 to v1.7):

```PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The service "rollerworks\component\passwordstrength\validator\constraints\blacklistvalidator" must be public as it can be lazy-loaded. in /var/www/myproject/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/AddConstraintValidatorsPass.php:35```

If I put the service ```Rollerworks\Component\PasswordStrength\Validator\Constraints\BlacklistValidator``` to ```public="true"```, it works.

**Comment by sstok** [comment]
Thanks for reporting, I will take care of it 👍

**Comment by sstok** [comment]
Fixed in v1.7.1
